.PHONY: all green2019 green2020 yellow2019 yellow2020 fhv2019

# Default target: run all
all: green2019 green2020 yellow2019 yellow2020 fhv2019

green2019:
    uv run main.py download-and-load green 2019

green2020:
    uv run main.py download-and-load green 2020

yellow2019:
    uv run main.py download-and-load yellow 2019

yellow2020:
    uv run main.py download-and-load yellow 2020

fhv2019:
    uv run main.py download-and-load fhv 2019
